---
 - hosts: all

   vars:
     #expected_checksum: 133fd85bcd79ed048a897be3a3f3bd4a2e9c616a
     #branch_target: testnet
     dest_path: /home/tddr/sui
     node_service_name: sui-node
     binary_source: ~/sui/target/release/sui-node
     binary_dest: /opt/sui/bin/sui-node
     script_source: compare.sh
     script_dest: ~/sui/compare.sh


   tasks:

   - name: 1- Delete sui directory directory
     ansible.builtin.file: 
      path: "{{ dest_path }}"
      state: absent

   - name: 2- Clone sui github repository for testnet branch
     ansible.builtin.git:
       repo: https://github.com/MystenLabs/sui.git
       dest: "{{ dest_path }}"
       version: "{{ branch_target }}"

   - name: 3- Copy script
     ansible.builtin.copy:
       src: "{{ script_source }}"
       dest: "{{ script_dest }}"
       mode: a+x
       force: yes

   - name: 4- Compare the checksum
     ansible.builtin.command: ~/sui/./compare.sh 'cd "{{ dest_path }}" && git rev-parse HEAD' "{{ expected_checksum }}"
     register: compare
   - name: show output for compare
     debug: 
       var: compare.stdout

   - name: 5- Update sui-client
     ansible.builtin.command: cargo build --bin sui --release
     args:
       chdir: "{{ dest_path }}"
     register: sui_client
   - name: show output for update sui-client
     debug: 
       var: sui_client.stdout

   - name: 6- Update sui-node
     ansible.builtin.command: cargo build --release --bin sui-node
     args:
       chdir: "{{ dest_path }}"
     register: sui_node
   - name: show output for update sui-node
     debug: 
       var: sui_node.stdout

   - name: 7- Stop Node Service if running
     become: true
     ansible.builtin.systemd:
       name: "{{ node_service_name }}"
       state: stopped
       
   - name: 8- Copy binary
     become: true
     ansible.builtin.copy:
       src: "{{ binary_source }}"
       dest: "{{ binary_dest }}"
       force: yes
       
   - name: 9- Start Node Service
     become: true
     ansible.builtin.systemd:
       name: "{{ node_service_name }}"
       state: started
       

